### PR TITLE
RELAYMSG sending support

### PR DESCRIPTION
**Pull request by hifi**
We are now draft/relaymsg aware enough to send them and filter out
our own relayed messages.

The tag after relayed name defaults to "m" and is configurable with
RELAYTAG plumbed room command.

### CODE REVIEW

**Comment by hifi** [comment]
Pushed to master.

**Comment by poVoq** [comment]
Super cool!

Is there documentation for this? I guess the plumbing bot needs OPER rights in the IRC channel?

**Comment by hifi** [comment]
No docs as usual :sweat_smile: 

`CAPS --add draft/relaymsg` in the network room, reconnect and see that the bot has requested and got it during connect. Join it to a channel (with `PLUMB` if it already isn't), op it and it may work.

You can change the tag/postfix (defaults to `m`) with `ROOM #plumbed-channel RELAYTAG <new tag>`.

It does indeed require some privileges in channels to be able to RELAYMSG and there's no fallback so if it's missing privs it'll get errors in the network room and be silent on IRC.

**Comment by poVoq** [comment]
Confirmed working with Conduit.

**Pull request closed without merging**
