### PR TITLE
More mypy

### PR DESCRIPTION
**Pull request by piegamesde**
The init methods got removed and replaced by proper constructors, where possible. I don't really know if the code actually works, so handle with care ^^.

### CODE REVIEW

**Comment by hifi** [comment]
Bear in mind the constructor and static create were for different purposes. The create method was to asynchronously create a new room in the homeserver and the constructor is only used to set a default/known state.

**Comment by piegamesde** [comment]
Okay. I figured that the create method was async, and thus merged the non-async ones with the constructor. The problem is that we cannot have a "blank" constructor, if we want this to typecheck, we *must* set some sensible values to all variables that may not be `None`. Also I didn't see any instances where objects were created using the constructor instead of `create`, but maybe I missed some important cases.

**Comment by hifi** [comment]
They are indirectly used here when loading from homeserverb

https://github.com/hifi/heisenbridge/blob/master/heisenbridge/__main__.py#L376

**Comment by piegamesde** [comment]
Thanks for the notice, this pretty much won't work. We need to be able to fully initialize an object within one method call. Because otherwise, one could forget to call `from_config`, leaving the object in an invalid state.

I could try making `from_config` a class method and see if `cls.from_config` works.

**Comment by hifi** [comment]
Maybe this could be looked at from a new angle based on the requirements of Rooms:

 1. it has a Matrix ID but it can be `None` until it has been created on Matrix side
 2. it has a corresponding Matrix `user_id` who "owns" the room
 3. it has members but depending on the room type there are valid and invalid members that can be in it
    - ControlRoom can only have two members: the owner and bridge, it becomes invalid when the owner leaves or there's more than two members in it
    - NetworkRoom can at most have two members: the owner and bridge, it becomes invalid when the owner leaves the room and the IRC connection is in manual disconnect state (aka `DISCONNECT` command has been issued or never connected) or a third member somehow gets in (shouldn't be possible)
    - PrivateRoom can at most have three members, the owner, bridge and an IRC puppet, it never becomes invalid as long as the puppet and bridge are in it, the owner will be invited back if they receive a message and the room is closed, it would go invalid if a fourth member would be added but it shouldn't be possible
    - ChannelRoom has at least two members: the owner and bridge, if the owner leaves the room becomes invalid (and is PARTed from IRC), puppets are in the room when IRC users join/leave but are not part of the validity check
   4. it has a config json state stored by the appservice that is a basic key-value store for per-room configuration data like the owner id, room name/target, network name, private message target, channel name, channel key for password protected channels and NetworkRooms have a lot of user configutable settings like nickname etc.
 
Creating a room from an IRC event (a response to PRIVMSG or JOIN) is a synchronous operation where the room object needs to be created for buffering purposes (events that come after JOIN or multiple PRIVMSGs) and attached to the IRC event handler but as the Matrix end is asynchronous it will not have an id immediately. The IRC buffer will be flushed to Matrix once the async create returns and it has an id.

Creating a room from a Matrix event (invite+join for ControlRoom by a user or create+invite for NetworkRoom by bridge) can not have corresponding IRC events so they are fire and forget. Though unlike ControlRoom a NetworkRoom does receive IRC events but as the room itself owns the connection there's no race condition possible.

Loading a room from HS happens by getting a list of joined rooms of the bridge, iterating over them, fetching the stored configuration, figuring out what Room class corresponds to it, requesting the member list of the room and somehow constructing the room object with all of this and finally telling NetworkRooms they can reconnect if they are in configured connected state. Glueing PrivateRooms and ChannelRooms to NetworkRooms is currently done by NetworkRoom during connect so they get IRC events and can send IRC commands through the NetworkRoom.

The main appservice event handler for Matrix events passes them on to whatever Room object is the target of an event.

**Comment by piegamesde** [comment]
The harder I try, the more I realize that this needs to be done by somebody already familiar with the whole code base. I am sorry, but I think I must pass on this one.

I'll be happy to help review any refactorings as well as I can, and I will continue my quest for full type checking after this is resolved.

**Pull request closed without merging**
