### PR TITLE
Implement kickban

### PR DESCRIPTION
**Pull request by blastrock**
Hi there,

Here is a PR to implement the kb command. It will ban a user and then kick them.

To ban the user, we first do a WHOIS to get their host. At the end of the WHOIS, we set the ban and kick them.

### CODE REVIEW

**Comment by hifi** [comment]
Could you add for safety that the pending list is cleared on reconnection at the same point where `whois_data` is?

Thanks!

**Comment by blastrock** [comment]
Right, done :)

**Comment by hifi** [comment]
Merged, thanks!

**Comment by blastrock** [comment]
Thanks to you! :)

**Pull request merged**
